version: '3.4'
#https://www.youtube.com/watch?v=3lOrtJtG2rw
services:
  manager.backend.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "56760:80"
   
  managersqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"